language: java
jdk:
  - oraclejdk7
  - openjdk7

before_install:
  - wget -P $TRAVIS_BUILD_DIR/ https://github.com/BitsAndPixels/jrpg-2017a-dominio/raw/master/build/libs/jrpg-2017a-dominio-0.1.jar
  - wget -P $TRAVIS_BUILD_DIR/ https://github.com/BitsAndPixels/jrpg-2017a-cliente/raw/master/build/libs/jrpg-2017a-cliente-0.1.jar